version: '3'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: cubeearth/forward-proxy
    volumes:
    - $HOME/.containers/squid/cache:/cache:rw
    ports: 
    - "3128:3128"
    - "3129:3129"
    - "3130:3130"
