apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-proxy
  labels:
    app: forward-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forward-proxy
  template:
    metadata:
      labels:
        app: forward-proxy
    spec:
      containers:
      - name: forward-proxy
        image: cubeearth/forward-proxy:latest
        ports:
        - containerPort: 3128        
---   
apiVersion: v1
kind: Service
metadata:
  name: forward-proxy
spec:
  selector:
    app: forward-proxy
  ports:
  - name: squid1
    port: 3128
